### ISSUE TITLE
Users can find any location on the map by providing an address

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will have the ability to find any location on the map by providing an address
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have the ability to input an address into a form field. Once submitted, the tool will display the given location on the map and automatically bring up a popup window that includes information about that place (latitude/longitude, geocoded address, elevation). The popup will also include additional buttons that lead to other features.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Popup Window](https://user-images.githubusercontent.com/25317196/172289536-da94aa1b-4aec-4176-9da7-9a9b9a7a7bed.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create the top banner that says travel app
- [x] Create a div element that serves as the map container
- [x] Create geocode input and place over the map canvas using absolute positioning contained in a form
- [x] listen for submits on the forms
  - [x] Geocode submit will call the geocode endpoint of openrouteservice and return data
  - [x] Geocode submit will call the elevation endpoint of openrouteservice and return data
  - [x] Once the data is returned create a popup window that includes 
    - [x] found address
    - [x] latitue/longitude
    - [x] elevation
  - [x] Once data is returned create a popup window that includes
    - [x] found address
    - [x] latitude/longitude
    - [x] elevation
  - [x] Include 3 buttons in popup window
    - [x] Directions button
    - [x] POI's button
    - [x] Clear button
