### ISSUE TITLE
Users can find any location on the map by providing latitude/longitude 

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will have the ability to find any location on the map by providing latitude/longitude
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have the ability to input a latitude/longitude pair into a form field. Once submitted, the tool will display the given location on the map and automatically bring up a popup window that includes information about that place (latitude/longitude, nearest associated address, elevation). The popup will also include additional buttons that lead to other features.## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop - Reverse Geocode](https://user-images.githubusercontent.com/25317196/172294884-5b45c6ce-660b-4c0f-83ea-1c81c6babb70.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Using 12 column layout create 3 column wide div element that serves as reverse geocode form
- [x] Once the dropdown button is clicked show the reverse geocode form
  - [x] include a label and input for latitude/longitude
  - [x] include a submit button
- [x] Listen for submits on the form
  - [x] Reverse geocode submit will call the reverse geocode endpoint and return data
  - [x] Reverse geocode submit will call the elevation endpoint and return data
  - [x] Once the data is returned create a popup window that includes
    - [x] latitude/longitude
    - [x] nearest found address
    - [x] elevation
  - [x] Include 3 buttons in the popup window
    - [x] Directions button
    - [x] POI's button
    - [x] Clear button
