### ISSUE TITLE
User can click the map and see information about the clicked location

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will have the ability to click on the map and see information about the clicked location
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click on the map and automatically see a popup window that includes information about that clicked place (latitude/longitude, geocoded address, elevation). The popup will also include additional buttons that lead to other features.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop - Reverse Geocode](https://user-images.githubusercontent.com/25317196/172295822-87e4a3df-b57d-411e-8702-afa834722310.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create an event listener on the map object that gets the clicked coordinates
- [x] Send an http request to the reverse geocode endpoint with the clicked coordinates used as inputs
- [x] Send an http request to the elevation endpoint with the clicked coordinates used as inputs
- [x] Once data is returned automatically create a popup window that includes
  - [x] latitude/longitude
  - [x] nearest found address
  - [x] elevation 
- [x] Include 3 buttons in the popup window
  - [x] Directions button
  - [x] POI's button
  - [x] Clear button
