### ISSUE TITLE
Users can get driving directions from a geocoded/reverse geocoded point, or clicked point, to another place

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can get driving directions from a geocoded/reverse geocoded point, or clicked point, to another place
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will have the ability to select the "directions" button from the popup window that displays upon geocoding/reverse geocoding, or clicking, any place. The button click will bring up a form in the left hand menu that automatically includes the selected starting point. The form will allow the user to input a second point and submit. The map will then display the directions/route.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop - Get Directions](https://user-images.githubusercontent.com/25317196/172296767-197eca0c-174e-40c3-8f37-0eeaeea2787e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create an event listener on the "directions" button that appears once a place has been selected
- [x] Display a "Get Directions" dropdown in the left hand menu
- [x] Automatically include the starting latitude/longitude point from the pre-selected place
- [x] Include an end point label and input that the user can add a second latitude/longitude to
- [x] On submit call the directions endpoint and return the geojson route
- [x] Display route on the map
- [x] Include markers on the start and end points
- [x] Center the map on the route
- [x] Toggle the directions menu when the form is submitted (to hide it, only accessible from a popup)
