### ISSUE TITLE
User can find nearby POI's to a place

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can find nearby POI's to a place
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will have the ability to select the "POI's" button from the popup window that displays upon geocoding/reverse geocoding, or clicking, any place. The button click will bring up a form in the left hand menu that automatically includes the selected starting point. The form will allow the user to input a buffer distance and submit. The map will then display the nearby POI's within the buffer distance.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop - Nearby POI's](https://user-images.githubusercontent.com/25317196/172297263-6ab2e75e-cd2e-4a61-9985-87b60282e8be.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create an event listener on the "POI's" button that appears once a place has been selected
- [x] Display a "Nearby POI's" dropdown in the left hand menu
- [x] Automatically include the starting latitude/longitude point from the pre-selected place
- [x] Include a buffer distance label and input that the user can add a buffer distance to
- [x] On submit call the POI's endpoint and return the nearest POI's
- [x] Display POI's on the map
- [x] Include markers on each found POI
- [x] Add an event listener to each marker and display a popup on click that shows the name, address, lat/lng of the POI
